apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tsjwt-system
resources:
  - controller.yaml
  - rbac.yaml
images:
  - name: tsjwt
    newName: ghcr.io/bitcomplete/tsjwt
    newTag: latest
